In [2]:
import numpy as np
import torch

In [4]:
# 1D array

t = torch.FloatTensor([0,1,2,3,4,5,6])
print(t)

print(t.dim())  # rank
print(t.shape)  # shape
print(t.size()) # shape
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [5]:
# 2D Array

t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

print(t.dim())  # rank
print(t.size()) # shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [ ]:
# 3D Array

# (batch, width, height) = (세로, 가로, 깊이)

In [6]:
# Broadcasting

# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[5., 5.]])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [7]:
# Mul vs. Matmul

# 일반적인 행렬의 곱셈은 사이즈가 같아야 함
# 만약 같지 않다면 자동으로 broadcast 되어 곱해짐
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))


# matmul
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [13]:
# mean

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.mean())  # 모든 수의 평균
print(t.mean(dim=0))  # 첫번째 열기준 
print(t.mean(dim=1))  # 두번째 열기준
print(t.mean(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [14]:
# sum

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [18]:
# max 

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print()

print(t.max()) # 모든 원소 중 가장 큰 것 반환
print()

print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])  # 열별로 가장 큰 값 반환
print('Argmax: ', t.max(dim=0)[1])  # 열별로 가장 큰 값의 인덱스 반환
print()

print(t.max(dim=1)) # Returns two values: max and argmax

tensor([[1., 2.],
        [3., 4.]])

tensor(4.)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [20]:
# View (Reshape)
# tensor 안에 있는 값들을 차례대로 나열하여 다시 재배열 하는 것

t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)
print()

# 사이즈가 -1이면 다른 차원으로 해당 값을 유추함
print(ft.view([-1, 3]))  # 2차원으로 만들고, 열의 개수를 3개로 해라
print(ft.view([-1, 3]).shape)
print()

print(ft.view([-1, 1, 3]))  # 3차원으로 만들고, width=1, height=3으로 해라
print(ft.view([-1, 1, 3]).shape)

torch.Size([2, 2, 3])

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])



In [27]:
# Squeeze
# element의 개수가 1인 차원을 삭제

ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

print()
print(ft.squeeze())
print(ft.squeeze().shape)  # 두번째 차원이 제거되어 1차원 벡터가 됨 
print()

# 특정 차원만 지우고 싶을때
ft2 = torch.FloatTensor([[[0], [1], [2]]])
print(ft2)
print(ft2.shape)
print()

print(ft2.squeeze(0))
print(ft2.squeeze(0).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])

tensor([0., 1., 2.])
torch.Size([3])

tensor([[[0.],
         [1.],
         [2.]]])
torch.Size([1, 3, 1])

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [28]:
# Unsqueeze
# 특정 위치에 element 개쉬가 1인 차원을 추가

ft = torch.Tensor([0, 1, 2])
print(ft.shape)
print()

print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

torch.Size([3])

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [31]:
# Casting
# 자료형을 변환하는 것

# 32비트의 부동 소수점은 torch.FloatTensor 사용
ft = torch.FloatTensor([1, 2, 3, 4])
print(ft)
print()

# 64비트의 부호 있는 정수는 torch.LongTensor를 사용
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())  # .float()을 붙이면 float 형으로 변경됨
print()

# Byte 타입의 bt라는 텐서
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())  # .long()이라고하면 long 타입의 텐서로 변경
print(bt.float())  # .float()이라고 하면 float 타입의 텐서로 변경

tensor([1., 2., 3., 4.])

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [32]:
# Concatenate
# 두 텐서를 연결하는 방법
# 두 텐서를 연결한다는 것은 두 가지의 정보를 모두 사용한다는 의미

x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
print(torch.cat([x, y], dim=0))  # 첫 번째 차원을 늘려라
print(torch.cat([x, y], dim=1))  # 두 번째 차원을 늘려라

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [34]:
# Stacking
# 세개 이상의 텐서를 연결하는 방법

x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [36]:
# ones_like, zeros_like 

x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기
print()

print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [37]:
# In-place Operation (덮어쓰기)

x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력
print()

# 연산 뒤에 _를 붙이면 기존의 값을 덮어쓰기
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


In [38]:
# Scatter (for one-hot encoding)
# scatter(dim, index, src): 1차원의 값을 인덱스로 1을 넣어라

lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)  # 1차원의 값을 인덱스로 1을 넣어라
print(one_hot)

tensor([[0],
        [1],
        [2],
        [0]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])
